# Generated by Django 5.2.8 on 2025-11-15 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default='Admin', max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CSVUploadHistory',
                'ordering': ['-upload_time'],
            },
        ),
    ]
