# Generated by Django 5.2.8 on 2025-11-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvuploadhistory',
            name='details',
        ),
        migrations.RemoveField(
            model_name='csvuploadhistory',
            name='status',
        ),
    ]
