# Generated by Django 5.2.8 on 2025-11-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvuploadhistory',
            old_name='filename',
            new_name='file_name',
        ),
    ]
