# Generated by Django 5.2.8 on 2025-11-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_remove_csvuploadhistory_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=150)),
                ('log_code', models.CharField(max_length=10)),
                ('log_date', models.DateField()),
                ('log_time', models.CharField(max_length=10)),
                ('upload_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanresource.csvuploadhistory')),
            ],
            options={
                'db_table': 'PayrollRecord',
                'ordering': ['employee_name', 'log_date', 'log_time'],
            },
        ),
    ]
