# Generated by Django 5.2.8 on 2025-11-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_rename_filename_csvuploadhistory_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvuploadhistory',
            name='uploaded_by',
            field=models.CharField(default='hr', max_length=100),
        ),
    ]
