# Generated by Django 5.2.8 on 2025-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0003_alter_csvuploadhistory_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadhistory',
            name='processed_data_json',
            field=models.JSONField(default=list),
        ),
    ]
