# Generated by Django 5.2.8 on 2025-11-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0003_payrollrecord'),
        ('humanresource', '0004_csvuploadhistory_processed_data_json'),
    ]

    operations = [
    ]
