# Generated by Django 5.2.8 on 2025-11-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0005_merge_20251119_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvuploadhistory',
            name='processed_data_json',
        ),
    ]
