# Generated by Django 5.0.2 on 2025-11-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0008_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee Record', 'verbose_name_plural': 'Employee Records'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_employee_id', models.CharField(max_length=50, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='humanresource.employee')),
            ],
            options={
                'db_table': 'EmployeeMapping',
            },
        ),
    ]
