# Generated by Django 5.0.2 on 2025-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0009_alter_employee_options_remove_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_separated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependent_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependent_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependent_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependent_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependent_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='educ_attainment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Educational Attainment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='extension_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension Name (Jr., Sr.)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly/Daily Rate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_of_dependents',
            field=models.IntegerField(default=0, verbose_name='No. of Dependents'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pag-IBIG No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PhilHealth No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='retirement_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Spouse Birthdate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SSS Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN'),
        ),
    ]
