# Generated by Django 5.0.2 on 2025-11-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0010_employee_address_employee_age_employee_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
