# Generated by Django 5.0.2 on 2025-11-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0002_admin_password_admin_username_alter_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
