# Generated by Django 5.2.8 on 2025-11-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0003_alter_admin_password_alter_admin_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='username',
            field=models.CharField(default='username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
