# Generated by Django 5.2.8 on 2025-11-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0004_regularuser_password_regularuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regularuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='regularuser',
            table='regularuser',
        ),
    ]
