# Generated by Django 5.2.8 on 2025-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0005_alter_admin_options_alter_regularuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
