# Generated by Django 5.2.8 on 2025-11-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0007_usersaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterModelTable(
            name='usersaccount',
            table='Users',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
    ]
