# Generated by Django 5.2.8 on 2025-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0008_usersaccount_role_alter_usersaccount_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-15 11:45:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Accounting', 'Accounting'), ('hr', 'HR'), ('timekeeper', 'Timekeeper')], default='Admin', max_length=50),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
